spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: rating.exchange
  routing-key: rating.created

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka