spring.application.name=rating-service

# Database URL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/order_service}

# Database username
spring.datasource.username=${DB_USERNAME:root}

# Database password
spring.datasource.password=${DB_PASSWORD:password}

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
#spring.jpa.show-sql=true

# Format SQL for readability
#spring.jpa.properties.hibernate.format_sql=true

server.port=8084